src/main/resources/schema/tables/job_test.sql

close #5
- 실무 테스트 db 생성 DDL 업로드

[feat] 실무 테스트 관련 테이블 생성

---

build.gradle
src/main/java/com/piveguyz/empickbackend/Application.java
src/main/java/com/piveguyz/empickbackend/calculator/query/controller/CalculatorQueryController.java
src/main/java/com/piveguyz/empickbackend/calculator/query/dto/AddRequestDto.java
src/main/java/com/piveguyz/empickbackend/calculator/query/dto/SubtractRequestDto.java
src/main/java/com/piveguyz/empickbackend/calculator/query/service/CalculatorQueryService.java
src/main/java/com/piveguyz/empickbackend/common/config/EncodingConfig.java
src/main/java/com/piveguyz/empickbackend/common/config/SecurityConfig.java
src/main/java/com/piveguyz/empickbackend/counter/query/controller/CounterQueryController.java
src/main/java/com/piveguyz/empickbackend/counter/query/service/CounterQueryService.java
src/main/java/com/piveguyz/empickbackend/interviewScore/command/application/dto/InterviewScoreCommandDTO.java
src/main/java/com/piveguyz/empickbackend/interviewScore/command/domain/aggregate/InterviewScoreEntity.java
src/main/java/com/piveguyz/empickbackend/interviewScore/query/dto/InterviewScoreQueryDTO.java
src/main/java/com/piveguyz/empickbackend/member/command/domain/aggregate/Member.java
src/main/java/com/piveguyz/empickbackend/member/command/domain/repository/MemberRepository.java
src/main/java/com/piveguyz/empickbackend/security/CustomMemberDetails.java
src/main/java/com/piveguyz/empickbackend/security/CustomMemberDetailsService.java
src/test/java/com/piveguyz/empickbackend/ApplicationTests.java
src/test/java/com/piveguyz/empickbackend/common/config/SecurityConfigTest.java
src/test/java/com/piveguyz/empickbackend/member/command/domain/repository/MemberRepositoryTest.java
src/test/java/com/piveguyz/empickbackend/security/CustomMemberDetailsServiceTest.java

close #15 
패키지 구조 변경(pive -> piveguyz)
----

[refactor] 패키지 구조 변경(pive -> piveguyz)

---

src/main/resources/application.yml
src/main/resources/schema/tables/application.sql
src/main/resources/schema/tables/introduce.sql

close #19
지원자 테이블, 지원자 북마크 테이블 추가

[feat] 지원자관련 테이블 추가

---

src/main/resources/schema/tables/recruitment.sql

close #55 
* 게시 시작일, 게시 마감일 컬럼 NOT NULL 변경
* 자기소개서 템플릿ID 컬럼 추가

[refactor] 채용공고 테이블 수정

---

src/main/resources/schema/tables/applicant.sql

close #100
application 테이블 순환 참조되던 외래키 칼럼 삭제

[refactor] 순환 참조되던 컬럼 삭제

---

src/main/resources/schema/tables/interview.sql
src/main/resources/schema/tables/mail.sql

[refactor] SQL drop 구문 추가

---

src/main/resources/schema/seed/role_insert.sql

close #1
직무 / 직업 / 직책 더미 데이터 생성
----

[feat] 부서, 직무 등 더미 데이터 일부 추가(사원 만들기용)

---

src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/controller/EvaluationCriteriaCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/dto/CreateEvaluationCriteriaCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/dto/EvaluationCriteriaCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/dto/UpdateEvaluationCriteriaCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/mapper/EvaluationCriteriaMapper.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/service/EvaluationCriteriaCommandService.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/service/EvaluationCriteriaCommandServiceImpl.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/domain/aggregate/EvaluationCriteriaEntity.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/domain/repository/EvaluationCriteriaRepository.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/controller/EvaluationCriteriaQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/dto/EvaluationCriteriaQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/mapper/EvaluationCriteriaMapper.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/service/EvaluationCriteriaQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/service/EvaluationCriteriaQueryServiceImpl.java
src/main/resources/mapper/jobtest/JobtestEvaluationCriteraMapper.xml

close #137
close #138 
close #139 
close #141
실무테스트 평가 기준 등록, 수정, 삭제 구현
실무테스트 평가 기준 조회, 상세 조회 구현
- 평가 기준 조회 : 특정 실무테스트에 관한 평가 기준
- 상세 조회 : 테스트용으로 만든 평가 기준 조회
평가 기준만 조회하는 경우는 없어서 전체 조회를 만들지 않았습니다.
----
- 실무테스트 평가 기준 등록
- 실무테스트 평가 기준 수정
- 실무테스트 평가 기준 삭제
- 실무테스트에 대한 평가 기준 조회 (jobtestId를 10으로 조회한 경우)
- 특정 평가 기준 조회 (id를 1로 조회한 경우)

[feat] 실무테스트 평가 기준 등록, 수정, 삭제. 조회 구현

---

src/main/java/com/piveguyz/empickbackend/common/handler/StepTypeHandler.java
src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/dto/RecruitmentCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/command/application/dto/RecruitmentProcessCreateDTO.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/command/domain/aggregate/RecruitmentProcess.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/command/domain/enums/StepType.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/command/domain/repository/RecruitmentProcessRepository.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/controller/RecruitmentProcessQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/dto/RecruitmentProcessQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/mapper/RecruitmentProcessQueryMapper.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/service/RecruitmentProcessQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/service/RecruitmentProcessQueryServiceImpl.java
src/main/resources/mapper/recruitment/RecruitmentProcessMapper.xml

close #145 
close #146 
close #147 
- [POST] 채용 공고 등록 (프로세스 포함)
localhost:5001/api/v1/employment/recruitment
```
{
"title": "백엔드 개발자 채용",
"content": "Spring Boot를 사용하는 백엔드 개발자 모집",
"recruitType": 0,
"imageUrl": "https://example.com/image.png",
"startedAt": "2025-06-15T00:00:00",
"endedAt": "2025-07-15T23:59:59",
"recruitmentTemplateId": 1,
"introduceTemplateId": 1,
"memberId": 1,
"recruitmentRequestId": null,
"applicationItems": [
{
"applicationItemCategoryId": 1,
"isRequired": true
},
{
"applicationItemCategoryId": 2,
"isRequired": false
}
],
"recruitmentProcesses": [
{
"stepType": "DOCUMENT",
"displayOrder": 1
},
{
"stepType": "PRACTICAL",
"displayOrder": 2
},
{
"stepType": "INTERVIEW",
"displayOrder": 3
}
]
}
```
* [PUT] 채용 공고 수정 (프로세스 포함) …

[feat] 채용공고별 프로세스 등록/수정/조회 기능 구현

---

src/main/java/com/piveguyz/empickbackend/member/query/controller/MemberQueryController.java
src/main/java/com/piveguyz/empickbackend/member/query/facade/MemberProfileQueryFacade.java

…ileQueryFacade를 퍼사드로 정리
- MemberQueryController를 MemberProfileQueryFacade와 AuthFacade에만 의존하도록 변경
----

[refactor] MemberQueryController의 퍼사드와 서비스 혼재 정리

---

src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceStandardQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardItemQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceStandardMapper.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryServiceImp.java
src/main/resources/mapper/introduce/IntroduceStandardItemMapper.xml
src/main/resources/mapper/introduce/IntroduceStandardMapper.xml

close #172 
자기소개서 기준표 항목 전체 조회

[feat] 자기소개서 기준표 항목 전체 조회

---

src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceStandardQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceStandardMapper.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryServiceImp.java
src/main/resources/mapper/introduce/IntroduceStandardMapper.xml

[feat] 자기소개서 기준표 전체 조회

---

src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/controller/AnswerCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/controller/GradingResultCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/controller/EvaluationCriteriaCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/controller/EvaluationResultCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/controller/EvaluationCriteriaQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/controller/EvaluationResultQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/controller/GradingCriteriaCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/ApplicationJobtestCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/JobtestCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/JobtestQuestionCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/ApplicationJobtestQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/JobtestQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionOptionCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/query/controller/QuestionQueryController.java

close #219
- api uri RESTful하게 수정
- swagger 형식 통일
- RESTful하지 않은 uri 가 있는지
- 실무테스트 관련인데 swagger로 묶이지 않은 기능이 있는지

[refactor] api 경로 수정, swagger tag 형식 통일

---

src/main/java/com/piveguyz/empickbackend/calculator/query/controller/CalculatorQueryController.java
src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
src/main/java/com/piveguyz/empickbackend/counter/query/controller/CounterQueryController.java
src/main/java/com/piveguyz/empickbackend/infra/s3/controller/S3Controller.java
src/main/java/com/piveguyz/empickbackend/orgstructure/department/command/application/controller/DeptChangeHistoryCommandController.java
src/main/java/com/piveguyz/empickbackend/orgstructure/department/query/controller/DeptChangeHistoryQueryController.java
src/main/java/com/piveguyz/empickbackend/orgstructure/department/query/controller/DeptMemberQueryController.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/controller/MemberCommandController.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/controller/MemberEditProposalCommandController.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/dto/ProposalStatusUpdateDTO.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/service/MemberEditProposalCommandService.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/service/MemberEditProposalCommandServiceImpl.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/controller/MemberQueryController.java

- 하위 도메인별 API 표시 형식으로 통일
----
<사원, 부서>
- 경로에 /search 제거
<S3>
<사원, 부서>
<S3>

[style] : 사원, 부서, S3 API doc 수정

---

src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/controller/ApplicationItemCategoryQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/controller/ApplicationItemQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/controller/RecruitmentCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/controller/RecruitmentQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/controller/RecruitmentProcessQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/application/controller/RecruitmentRequestCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/query/controller/RecruitmentRequestQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/command/application/controller/RecruitmentTemplateCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/query/controller/RecruitmentTemplateQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/query/controller/RecruitmentTemplateCopyQueryController.java

close #221 
* api 경로 수정
* swagger tag 형식 수정

[refactor] 채용공고 관련 도메인 api 경로, swagger tag 형식 수정

---

src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/controller/ApplicationResponseCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/dto/ApplicationResponseCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/mapper/ApplicationResponseCommandMapper.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicationResponseCommandService.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicationResponseCommandServiceImp.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/aggregate/ApplicationResponseEntity.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/repository/ApplicationResponseRepository.java

close #226 
지원서 항목별 내용 등록 개발
예외처리 추가 ( 응답 내용 공백 x , 응답 내용 중복 x )
----

[feat] 지원서 항목별 내용 등록

---

src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/controller/MailCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/mapper/MailCommandMapper.java

#39 
단순 이메일 발송 기능 리팩토링
----
localhost:5001/api/v1/employment/mail/send
@RequestBody
```
{
"email" : "tjalswhd1@naver.com",
"title" : "테스트 메일 제목",
"content" : "테스트 메일 내용"
}
```

[refactor] 단순 이메일 발송 기능 리팩토링

---

src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/controller/GradingCriteriaCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/dto/CreateGradingCriteriaCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/mapper/GradingCriteriaMapper.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/service/GradingCriteriaCommandService.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/service/GradingCriteriaCommandServiceImpl.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionOptionCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/dto/CreateQuestionOptionCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/dto/CreateQuestionResponseDTO.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/mapper/QuestionMapper.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/mapper/QuestionOptionMapper.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/service/QuestionCommandService.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/service/QuestionCommandServiceImpl.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/service/QuestionOptionCommandService.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/service/QuestionOptionCommandServiceImpl.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/query/dto/QuestionQueryDTO.java
src/main/java/com/piveguyz/empickbackend/facade/QuestionFacade.java
src/main/resources/mapper/jobtest/QuestionMapper.xml

close #243
- 프론트 데이터에 맞게 문제 등록 DTO 수정
- 문제 등록 facade 패턴 적용
- 문제 등록 시 선택지, 평가 기준에 questionId 자동 할당
----
- 선택형 문제 등록(선택지와 답안을 함께 등록)
```java
{
"content": "Java의 특징이 아닌 것은?",
"detailContent": "Java 특징",
"type": "MULTIPLE",
"difficulty": "EASY",
"answer" : 1,
"createdMemberId": 10,
"questionOptions": [
{
"content": "의존성 주입"
},
{
"content": "객체 지향 언어"
}
]
}
```
- 서술형 문제 등록(채점 기준과 함께 등록)
```java
{
"content": "문제 등록 테스트2",
"detailContent": "문제 등록 내용",
"type": "DESCRIPTIVE",
"difficulty": "EASY",
"createdMemberId": 10,
"gradingCriteria": [
{
"content": "핵심 키워드 포함 여부",
"detailContent": "캡슐화라는 단어가 포함되었는지 확인",
"scoreWeight": 0.5
},
{
"content": "설명의 논리성",
"detailContent": "개념 설명이 논리적인지",
"scoreWeight": 0.5
}
]
}
```
- 객관식 문제 등록
- 서술형 문제 등록

[refactor] 실무테스트 문제 등록 DTO 수정

---

src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicationQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicationMapper.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationQueryServiceImp.java
src/main/resources/mapper/applicant/applicationMapper.xml

[feat] 지원서 id로 조회

---

src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicantQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicantMapper.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantQueryServiceImp.java
src/main/resources/mapper/applicant/applicantMapper.xml

#85
지원자 id로 조회 / 이름으로 검색 기능 구현(Query)
----
[GET] localhost:5001/api/v1/employment/applicant/{id}
[GET] localhost:5001/api/v1/employment/applicant/search
@RequestParam("name")

[feat] 지원자 id로 조회 / 이름으로 검색 기능 구현(Query)

---

src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java

* 템플릿이 null일 경우 템플릿 조회 및 복사 로직 생략

[refactor] 채용공고 등록 시 공고 템플릿이 null인 경우 예외 처리

---

src/main/resources/schema/tables/approval.sql

[feat] 결재 관련 도메인 테이블 생성

---

src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicationQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicationMapper.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationQueryServiceImp.java
src/main/resources/mapper/applicant/applicationMapper.xml

#266 
지원자 id로 지원서 조회 기능 구현(query)
----
[GET] localhost:5001/api/v1/employment/application/applicant/{applicantId}
applicantId = 2000 으로 확인 가능

[feat] : 지원자 id로 지원서 조회 기능 구현(query)

---

src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/dto/IntroduceTemplateCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/mapper/IntroduceTemplateCommandMapper.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceTemplateCommandServiceImp.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceTemplateQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceTemplateQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceTemplateMapper.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceTemplateQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceTemplateQueryServiceImp.java
src/main/resources/mapper/introduce/IntroduceTemplateItemMapper.xml
src/main/resources/mapper/introduce/IntroduceTemplateMapper.xml

[feat] 자기소개서 페이지와 연동

---

src/main/java/com/piveguyz/empickbackend/auth/command/application/service/AuthCommandServiceImpl.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicantQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicantFullInfoDTO.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicantQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicantMapper.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantQueryServiceImp.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/controller/MemberQueryController.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/dto/MemberRoleQueryDTO.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/mapper/MemberMapper.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/service/MemberQueryService.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/service/MemberQueryServiceImpl.java
src/main/resources/mapper/applicant/applicantMapper.xml
src/main/resources/mapper/introduce/IntroduceStandardMapper.xml
src/main/resources/mapper/member/MemberMapper.xml

----
- http://localhost:5001/api/v1/employment/application

[feat] 지원자 전체 정보 조회

---

src/main/resources/mapper/recruitment/RecruitmentQueryMapper.xml

[hotfix] 삭제된 공고도 상세조회 가능하도록 쿼리 수정

---

src/main/java/com/piveguyz/empickbackend/approvals/approval/query/dto/ApprovalQueryDTO.java
src/main/java/com/piveguyz/empickbackend/approvals/approval/query/dto/ApprovalReceivedQueryDTO.java
src/main/resources/schema/tables/approval.sql

* 결재 차례인지를 나타내는 isMyTurn 추가
[GET] /api/v1/approval/received?memberId=10

[feat] 요청받은 결재 목록 DTO에 결재차례 추가

---

src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicantQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicantFullInfoDTO.java
src/main/resources/mapper/applicant/applicantMapper.xml

[feat] 지원자에 쿼리 데이터 추가

---

src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/controller/MemberQueryController.java

----
- 내 권한 조회 (로그인)
- 타사원 권한 조회 (사번)
<내 권한 조회>
<사원 권한 조회>
- http://localhost:5001/api/v1/members/roles?employeeNumber=100004 (사원)
- http://localhost:5001/api/v1/members/my-roles (내 권한)

[feat] 사원 권한 조회 (내권한, 타사원 권한)

---

src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/controller/MemberCommandController.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/controller/MemberQueryController.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/mapper/MemberMapper.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/service/MemberQueryService.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/service/MemberQueryServiceImpl.java
src/main/resources/mapper/member/MemberMapper.xml

- 사번을 넣지 않으면 전체 사원이 검색됨
----
- http://localhost:5001/api/v1/members

[refactor] 기존 사원 검색에 전체 사원 검색 기능 추가

---

src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceCategoryServiceImpl.java
src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceRecordResponseServiceImpl.java
src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceRecordServiceImpl.java

!hotfix : 잘 못 설정된 패키지명 수정

---

src/main/java/com/piveguyz/empickbackend/employment/interviews/facade/InterviewFacade.java
src/main/resources/mapper/interviewer/InterviewerMapper.xml

close #이슈번호
점수가 안 입력됐을경우 점수반영 제외 - 면접 점수 최신화 및 자동 계산 기능 구현
----
면접 평가 점수 등록 및 수정
면접 평가 기준 가중치 반영
면접 담당자 합산 점수 최신화
면접 총점 최신화
- 주요 로직

[refactor] 점수가 안 입력됐을경우 점수반영 제외 - 면접 점수 최신화 및 자동 계산 기능 구현

---

src/main/resources/schema/tables/introduce.sql

close #이슈번호
introduce_standard_item 테이블에 introduce_standard_id
컬럼 상태 not null에서 null로 변경
----

[!hotfix] 스키마 변경

---

src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
src/main/java/com/piveguyz/empickbackend/orgstructure/facade/MemberProfileFacade.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/controller/MemberCommandController.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/dto/MemberSignUpRequestDTO.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/service/MemberCommandServiceImpl.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/domain/aggregate/MemberEntity.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/controller/MemberQueryController.java

close #280 
- 프론트에서 책임지던 프로필 업로드 방식을 백엔드에서 통합 처리 하도록 변경
- 신규 회원 등록시 ROLE_USER 권한 자동 부여
----

[refactor] 프로필 이미지 업로드 방식 변경

---

src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceStandardQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceStandardMapper.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryServiceImp.java
src/main/resources/mapper/introduce/IntroduceStandardMapper.xml

close #이슈번호
자기소개서 기준표 id로 상세 조회 기능
----

[feat] 자기소개서 기준표 id로 상세 조회 기능

---

src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceStandardItemCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceStandardItemCommandService.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceStandardItemCommandServiceImp.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceStandardQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardItemQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceStandardMapper.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryServiceImp.java
src/main/resources/mapper/introduce/IntroduceStandardItemMapper.xml
src/main/resources/mapper/introduce/IntroduceStandardMapper.xml

[feat] 기준표id로 기준표 항목 전체 조회/ 기준표 항목 수정 기능 구현

---

src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/controller/MailCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/service/MailCommandService.java
src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/service/MailCommandServiceImpl.java
src/main/java/com/piveguyz/empickbackend/employment/mail/facade/MailFacade.java
src/main/resources/mapper/mail/MailMapper.xml

#60 
api 주소 변경( #{id} => #{applicationId}
실무테스트 안내 메일 발송 기능 / 면접 일정 안내 메일 발송 기능 매개변수 추가(발송자 id - senderId)
----

[refactor] api 요청 주소 변경 및 매개변수 추가

---

src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java

채용공고 수정 시 템플릿 미지정 허용 및 예외 처리
* 프론트엔드 feature/hm/recruitment_modify 브랜치에서 함께 확인부탁드립니다!
- [PUT] /api/v1/employment/recruitments/{id}

[refactor] 채용공고 수정 시 템플릿 미지정 허용 및 예외 처리

---

src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/JobtestCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/UpdateJobtestCommandDTO.java

close #이슈번호
- 실무테스트 수정에 필요한 DTO로 수정
-----
- 아직 서비스를 수정하지 않아서 수정 기능은 동작하지 않습니다!
- PR이 쌓이기 전에 DTO 수정사항만 업로드한 상태입니다.

[refactor] 실무테스트 수정 관련 DTO 수정

---

src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicationCommandServiceImp.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/dto/IntroduceRatingResultCreateCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/mapper/IntroduceRatingResultCommandMapper.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/aggregate/IntroduceRatingResultEntity.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceResultQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceResultQueryDTO.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceMapper.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceQueryServiceImp.java
src/main/resources/mapper/introduce/introduceMapper.xml
src/main/resources/mapper/introduce/introduceResultMapper.xml
src/main/resources/schema/tables/all.sql

close #이슈번호
introduce / dto와 xml 수정 
조회 기능 추가
자소서 평가결과서 dto,mapper,entity 수정
지원서 업데이트 로직 리펙토링 
----
조회 /api/v1/employment/introduce/application/{applicationId}
조회 /api/v1/employment/introduce/{id}
수정 /api/v1/employment/application/{applicationId}

[ref] 자소서 dto,xml 수정/ introduce 조회기능 추가 /자소서 평가결과서 dto,mapper,entity 수정/ 지원서 업데이트 로직 리펙토링 

---

src/main/resources/templates/jobtest-mail-template.html

#60 
실무테스트 일정 안내 메일 템플릿 수정
----

[refactor] 실무테스트 일정 안내 메일 템플릿 수정

---

src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceResultQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceResultMapper.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceResultQueryService.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceResultQueryServiceImp.java
src/main/resources/mapper/introduce/introduceResultMapper.xml

close #이슈번호
자기소개서 평가 결과서 id로 조회
----
http://localhost:5001/api/v1/employment/introduce-result/{introduceResultId}

[feat] 자기소개서 평가 결과서 id로 조회

---

src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/JobtestQuestionQueryDTO.java
src/main/resources/mapper/jobtest/JobtestMapper.xml

close #이슈번호
- 실무테스트 조회할 때 나오는 등록 문제 DTO에 문제 유형 추가

[refactor] 실무테스트 조회 시 문제에 유형 추가

---

src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/aggregate/ApplicationStatus.java

close #이슈번호
지원서 상태 enum 수정
----

[ref] 지원서 상태 enum 수정

---

src/main/resources/schema/tables/all.sql

[ref] 프론트 지원서 상태와 연동된 스키마 최신화

---

src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/UpdateJobtestCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/JobtestCommandServiceImpl.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/ApplicationJobtestRepository.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/JobtestQuestionRepository.java

close #이슈번호
프론트 PR https://github.com/Pive-Guyz/be14-fin-Empick-FE/pull/188 과 함께 테스트/PR 부탁드립니다!

[refactor] 실무테스트 수정 구현

---

src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/scheduler/RecruitmentStatusScheduler.java

채용공고 게시 상태 변경 주기 매시 정각 -> 매분 0초로 수정

refactor: 채용공고 게시 상태 변경 주기 1분으로 수정

---

src/main/java/com/piveguyz/empickbackend/common/util/PasswordEncoder.java

#1 
사원 비밀번호 데이터 생성을 위한 비밀번호 인코더 구조 수정(반복 동작)
----
java.com.piveguyz.empickbackend.common.util.PasswordEncoder

[refactor] 사원 비밀번호 데이터 생성을 위한 비밀번호 인코더 구조 수정(반복 동작)

---

src/main/java/com/piveguyz/empickbackend/common/config/SecurityConfig.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/controller/ApplicantBookmarkCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/controller/ApplicantCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/controller/ApplicationCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/controller/ApplicationResponseCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicantBookmarkQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicantQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicationQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicationResponseQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/controller/ApplicationItemCategoryQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/controller/ApplicationItemQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceRatingResultCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceStandardCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceStandardItemCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceTemplateCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceTemplateItemCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceTemplateItemResponseCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceResultQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceStandardQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceTemplateItemResponseQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceTemplateQueryController.java

[ref] 스웨거 tag 통일

---

src/main/java/com/piveguyz/empickbackend/common/config/OpenApiConfig.java
src/main/java/com/piveguyz/empickbackend/common/config/SecurityConfig.java
src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicantCommandServiceImp.java

[ref] 지원자에 대한 이메일,전화번호 중복처리 삭제

---

src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/controller/ApprovalCommandController.java
src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/dto/CreateApprovalCommandDTO.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/controller/AnswerCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/controller/GradingResultCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/query/controller/AnswerQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/controller/EvaluationCriteriaCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/controller/EvaluationResultCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/controller/EvaluationCriteriaQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/controller/EvaluationResultQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/controller/GradingCriteriaCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/ApplicationJobtestCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/JobtestCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/JobtestQuestionCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/JobtestQuestionRepository.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/ApplicationJobtestQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/JobtestQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionOptionCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/query/controller/QuestionQueryController.java
src/test/java/com/piveguyz/empickbackend/approvals/approval/command/ApprovalCommandTest.java
src/test/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/AnswerCommandTest.java
src/test/java/com/piveguyz/empickbackend/employment/jobtests/answer/query/AnswerQueryTest.java
src/test/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/ApplicationJobtestCommandTest.java
src/test/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/JobtestCommandTest.java
src/test/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/JobtestQuestionCommandTest.java
src/test/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/ApplicationJobtestQueryTest.java
src/test/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/JobtestQueryTest.java
src/test/java/com/piveguyz/empickbackend/employment/jobtests/question/command/QuestionCommandTest.java
src/test/java/com/piveguyz/empickbackend/employment/jobtests/question/command/QuestionOptionCommandTest.java
src/test/java/com/piveguyz/empickbackend/employment/jobtests/question/query/QuestionQueryTest.java

close #이슈번호
- 결재 command 단위테스트 구현
- 실무테스트 관련 기능 단위테스트 구현
린샷

[test] 결재 command / 실무테스트 단위테스트 구현

---

src/main/java/com/piveguyz/empickbackend/auth/command/application/controller/AuthCommandController.java
src/main/java/com/piveguyz/empickbackend/common/config/SecurityConfig.java
src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/controller/MemberCommandController.java

- http://localhost:8080/career/recruitments/

!hotfix : 비회원 지원서 흐름 시큐리티 등록

---

src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/controller/ApprovalCommandController.java
src/main/java/com/piveguyz/empickbackend/approvals/approval/query/controller/ApprovalDetailQueryController.java
src/main/java/com/piveguyz/empickbackend/approvals/approval/query/controller/ApprovalLineQueryController.java
src/main/java/com/piveguyz/empickbackend/approvals/approval/query/controller/ApprovalQueryController.java
src/main/java/com/piveguyz/empickbackend/approvals/approvalCategory/query/controller/ApprovalCategoryQueryController.java
src/main/java/com/piveguyz/empickbackend/approvals/approvalCategoryItem/query/controller/ApprovalCategoryItemQueryController.java
src/main/java/com/piveguyz/empickbackend/approvals/approvalContent/query/controller/ApprovalContentQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/controller/RecruitmentCommandController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/controller/RecruitmentQueryController.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/command/application/dto/RecruitmentProcessCreateDTO.java
src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/application/controller/RecruitmentRequestCommandController.java
src/test/java/com/piveguyz/empickbackend/employment/recruitment/RecruitmentCommandTest.java
src/test/java/com/piveguyz/empickbackend/employment/recruitment/RecruitmentQueryTest.java
src/test/java/com/piveguyz/empickbackend/employment/recruitment/RecruitmentRequestCommandTest.java
src/test/java/com/piveguyz/empickbackend/employment/recruitment/RecruitmentRequestQueryTest.java

- 채용 도메인 테이스 케이스 생성
- 결재 쿼리 스웨거 태그 정리

[test] 채용 도메인 테스트 케이스 생성/결재 쿼리 스웨거 태그 정리
